ERROR:TeleBot:ApiTelegramException occurred, args=('A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',)
Traceback (most recent call last):
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 285, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 255, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 241, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 108, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 135, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

ERROR:TeleBot:A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
WARNING:root:WARNING with callback_inline
ERROR:root:ERROR with callback_inline
CRITICAL:root:CRITICAL with callback_inline
ERROR:TeleBot:ApiTelegramException occurred, args=('A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',)
Traceback (most recent call last):
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 285, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 255, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 241, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 108, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 135, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

ERROR:TeleBot:A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:TeleBot:ApiTelegramException occurred, args=('A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',)
Traceback (most recent call last):
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 285, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 255, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 241, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 108, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 135, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

ERROR:TeleBot:A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:TeleBot:ApiTelegramException occurred, args=('A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',)
Traceback (most recent call last):
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 285, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 255, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 241, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 108, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 135, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

ERROR:TeleBot:A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:TeleBot:ApiTelegramException occurred, args=('A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',)
Traceback (most recent call last):
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 285, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 255, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 241, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 108, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 135, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

ERROR:TeleBot:A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:TeleBot:ApiTelegramException occurred, args=('A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',)
Traceback (most recent call last):
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 285, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 255, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 241, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 108, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 135, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

ERROR:TeleBot:A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:TeleBot:ApiTelegramException occurred, args=('A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',)
Traceback (most recent call last):
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 285, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 255, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 241, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 108, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 135, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

ERROR:TeleBot:A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:TeleBot:ApiTelegramException occurred, args=('A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',)
Traceback (most recent call last):
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 285, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 255, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 241, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 108, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 135, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

ERROR:TeleBot:A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:TeleBot:ApiTelegramException occurred, args=('A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',)
Traceback (most recent call last):
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 285, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 255, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 241, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 108, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 135, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

ERROR:TeleBot:A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:TeleBot:ApiTelegramException occurred, args=('A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',)
Traceback (most recent call last):
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 285, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 255, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 241, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 108, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 135, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

ERROR:TeleBot:A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:TeleBot:ApiTelegramException occurred, args=('A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running',)
Traceback (most recent call last):
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 285, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 255, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 241, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 108, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Александр Хабаров\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\apihelper.py", line 135, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

ERROR:TeleBot:A request to the Telegram API was unsuccessful. Error code: 409 Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
